### ISSUE TITLE
Chat invisible

### ISSUE THREAD

**Issue by hellphish** [spencerhughes/docker-movienight#1]
When connecting to chat and posting, the messages are posted (confirmed in the console) but are invisible on the rendered web page. Using the inspector in Chrome you can see the that messages are there, but are invisible for some reason.

**Comment by spencerhughes** [comment]
I just rebuilt the image that's on Docker Hub, which should include the most up-to-date version of MovieNight. If the issue hasn't been resolved, you'll need to raise it with the MovieNight devs.

**Comment by hellphish** [comment]
I gave it another shot and still no dice. I'm not super-savvy with docker, but I did notice that your docker uses Go version 1.12.7 while the official repo states that the minimum requirement is 1.13 or newer.

**Comment by spencerhughes** [comment]
I updated Go to 1.13.10 and tested in Chromium on my Mac and it's working for me now. Care to give a shot?

**Comment by hellphish** [comment]
Sorry for the delay getting back to you. I ended up forking this and making nearly the exact same change you did, except I updated Go to 1.14.1.  It works for me now as well. I think we can close this.
